---
title: "Summaries"
author: "Robert Esposito & Kendra Dickinson, Ph.D."
format: pdf
---

# Article Summaries

Note: If I can't find the article yet, I just put the abstract. 

## @barnard2025listening
Barnard et al. examine whether listeners expend different amounts of cognitive effort when processing familiar and less-familiar L1 accents, as well as L2-accented speech, using pupillometry. For our purposes, their questionnaire is useful because it measures accent exposure across specific domains—social life, work/student life, and media—using a 7-point frequency scale from “almost never” to “daily,” allowing researchers to compare exposure to different accents or dialects in a systematic way.

## @hoffman2010ethnolects
Hoffman and Walker examine how ethnic orientation shapes linguistic variation in Toronto English, focusing on Italian and Chinese communities and arguing that ethnicity should be measured through both external social categories and speakers’ own self-identifications.For our purposes, the most useful takeaway is their *Ethnic Orientation questionnaire*, which measures ethnic identification, language use/choice, cultural heritage, family and partner practices, attitudes, and discrimination, and could serve as a reference point for developing a dialect-contact/identity questionnaire.

## @oushiro2020contrasting
The paper examines how age of arrival and length of residence affect dialect acquisition among forty Brazilian Portuguese speakers from Alagoas and Paraíba who migrated to the Campinas region of São Paulo. Oushiro analyzes two phonetic variables, coda /r/ and /t, d/ before [i], and two morphosyntactic variables, sentential negation and nominal agreement, comparing migrants’ speech with nonmigrant Northeasterners and native Paulistas. The results show that migrants generally adopt some Paulista or urban variants, but the predictors vary by linguistic feature: age of arrival is a stronger predictor than length of residence for phonetic accommodation, while length of residence only significantly predicts coda /r/, likely because of that variable’s salience. Self-reported identification with the home state or São Paulo also patterns phonetic and morphonsyntactic variables differently, and whether the variable indexes North-South or rural-urban distinctions. 


## @gubitosi2020portuguese

Overview article about Portuguese in Massachusetts. Does not deal with specific linguistic features, but rather, focuses on demographic and historical descriptions. Of utility for our purposes could be their examination of the role of social networks in attitudes towards Portuguese in MA.

Details that they have that we can include:

- census data and maps
- description of Portuguese-language establishments (e.g., churches, restaurants), newspapers, radio stations, TV stations, news stations, Instagram news outlets
- quotes about Portuguese from public school websites
- information about Portuguese classes in public schools

Language attitudes related to language maintenance, but interviews establish clearer connection than questionnaires [@cherciov2013investigating].

Social networks analyzed in three dimensions:

- relational characteristics
  - nature of the relationship (family, friend, colleague)
  - intensity of interactions (always, frequent, seldom)
  - divided into "primary" and "non-primary"
- structural properties
  - size of network
  - size of "primary" and "non-primary" networks
- location in space and time
  - relatives abroad
  - trips abroad

Gendered nature of language transmission. Bilingual responsabilities falls on mother typically. This study found that fathers are also important for language positivity.

## @milroy2013social

Social networks.

## @cunha2023attitudes

Dissertation about Heritage Speakers of Brazilian Portuguese in the U.S. Could be a useful reference for sociolinguistic questionnaire development. Also includes picture description task aiming to prompt past tense and general descriptions.

## @stephens1989language

Portuguese in USA. Arrivals began in 1820s, picked up in 1830s with arrival fo Lusitanian and Azorean. Congregated to New England, specifically MA. 1850s, to California (San Fran).

Late 19th/early 20th century, big influx to CA, MA, NY, & NJ. Mid-1970s, major immigration event.

Early immigrants = high illiteracy, low English.

Azorean Portuguese is stigmatized [@middleton1986language].

Began arriving to Newark in large groups in 1920s [@cunha1981portugueses].

Bilingual programs (I guess school programs?) & Sunday schools. 15 private Portuguese schools, similar to Hebrew schools.

## @carvalho2010portuguese

Portuguese immigrants mainly from Azores Islands, mainland Portugual, and Cape Verdean, smaller population from Mozambique and Angola. High concentrations in MA. Over last 20 years, Cape Verdeans & Brazilians account for most PT speakers.

14,829 students taking Portuguese classes in K-12 schools in 2008 [@vicente2008promoccao].

Modern Language Association in 2006 reported 22.4% increase of availability of Portuguese instruction between 2002 and 2006.

US Census underestimates PT speakers in USA. Ministry of Foreign Affairs in Brazil report much higher estimate. Due to undocumented immigrants.

National Bilingual Education Act of 1968 resulted in PT-EN bilingual education initiatives in 1970s.

Republic of Cape Verde immigrants speak a Portuguese-based creole and Portuguese. They typically are more receptive bilinguals than e.g., Azorean or Madeiran speakers in the US (Ferreira 2005; need to find bibtex). Cape Verdean-Americans tend to be L1 Crole L1 EN/L2 EN, and then may learn PT as L3 in school.

Brazilian immigration in 1984-1987, again in 1990s. Young, educated, middle-class men and women on tourist visas and overstayed (Bensabat-Ott 2000; need to find bibtex). Later, working class immigrants from small towns and rural areas who entered via US-Mexico border.

Luso-American Foundation (FLAD, Fundacao Luso-Americana de Desenvolvimento) identified `r 52 + 25 + 20 + 17 + 13 + 10 + 5 +1` K-12 public and community schools that offer Portuguese. 20 in NJ, 10 in NY, 13 in CT; weekend Portuguese language schools in NJ [@vicente2008promoccao].

Dual-immersion EN-PT program in K-8 school in MA resulted in greater awareness of dialectal differences among teachers, parents, and staff [@rubinstein2002problematizing].

Dialectal differences do not result in communicative breakdown between students (Rubinstein-Avila, 2002; Ferreira, 2005).

## @osborne2021perception

Mid vowel contrasts as the last to be acquired by L1 speakers (Matzenauer & Costa, 2017). Low functional load with few minimal pairs (Alves, 2008).

12 BR-PT heritage speakers. Completed BLP (all except one was English-dominant, but pretty large range).

AXB discrimination. Check article for list of stimuli.

2AFC identification task.

Heritage speakers accurately categorize PT mid vowels, but higher EN dominance predicted more trouble with /ɔ/-/o/. Amengual (2015) found the same asymmetry for ES-Catalan bilinguals. 

## @rothman2014portuguese

No studies examining Cape Verdean Portuguese as a heritage language. (Although, as noted by @carvalho2010portuguese, they would be learning Cape Verdean Creole at home).

PT-PT stops are pronounced as fricatives; BR-PT pronounces as plosives. Would be interesting to see if PT-PT maintains fricatives in Newark given input from BR-PT and English.

For our reference, this chapter also includes presents demographic information (though somewhat outdated, from 2000, 2008, etc.) on Portuguese speakers in the United States, including population size, growth over time, and age distribution. It also details ancestry groups (Portuguese, Brazilian, Cape Verdean) and their regional concentration across U.S. regions and states, along with data on English proficiency as an indicator of bilingualism and language shift. 

Summary of heritage speakers learning in college, focused on dialectal differences [@silva2010starting].

## @silva2010starting

Developing a heritage speaker track in college for PT. Focus on dialectal differences.

## @galves2005syntax
Syntactic position of clitic pronouns (e.g., *me, te, se, o, lhe*) in EP and BP arise from both syntactic and morphophonological factors. The authors argue that EP clitics attach to Infl (inflectional category) and BP clitics attach to the verb (V) in the syntactic structure. Additionally, the authors argue that EP does not permit clitics in sentence-initial position, whereas BP does not have this restriction. This results in a strong preference for enclisis (post-verbal clitic) in EP (*chamou-me*), and a preference for proclisis (pre-verbal clitic) in BP (*me chamou*). In multi-verb constructions, EP clitics attach to the finite verb (*tinham-se entendido perfeitamente*), while in BP they tend to attach to the non-finite verb (*tinham se entendido perfeitamente*)

## @amadeo2025perception

Escudero et al. (2009; "A cross-dialect acoustic description of vowels: Brazilian and European Portuguese) and Rato & Carlet (2020) show that BR-PT and PT-PT share some similarities in their vowel inventory.

Diaz-Granado (2011) found that /e ~ ɛ/ in English & Portuguese are not similar, so L1 En L2 Pt are expected to collapse PT /e ~ ɛ/ into a single category. Tested L1 En L2 Pt and L1 En L2 Es L3 Pt. L3 learners performed better. But there were only 12 in the first group, 5 in the second.

Kendall (2004) tested 20 beginning and advanced L1 En L2 Pt learners on BP mid vowels. They did poorly.

Vasiliev (2013) tested L1 English L2 Pt stressed oral vowels. /e ~ ɛ/ was second-easiest.

Elvin et al. (2018) L1 En monolinguals, En-Es bilinguals tested on discrimination task for Pt-Pt and Pt-Br. /o ~ ɔ/ easier in EP than BP, which was second-easiest to discriminate. Participants had more trouble with /i ~ e/ and /u ~ o/.

Summary: For L1 US En, /e ɛ o c/ are hardest to discriminate; /e ~ ɛ, o ~ ɔ, e ~ i, o ~ u/ are most challenging minimal pairs. These challenges are accurately predicted by perception models e.g., Escudero 2009.

NEED TO FINISH THIS SUMMARY AND ALSO FIND ALL OF THESE ARTICLES.

## @albano2021some

Review of laboratory phonology of Portuguese.

Vowel Variability: 

-   /a ɐ/: In EP.Northern EP losing /a ɐ/ distinction in stressed syllables in perception. (From [Wikipedia](https://en.wikipedia.org/wiki/Portuguese_phonology): "In central European Portuguese this contrast occurs in a limited morphological context, namely in verb conjugation between the first person plural present and past perfect indicative forms of verbs such as pensamos ('we think') and pensámos ('we thought'; spelled ⟨pensamos⟩ in Brazil)." I would assume this contrast gets lost pretty quickly in diaspora.

-   Vowel-to-vowel interactions across syllables (metaonymy; vowel harmony). Morphologized influence of a truncated theme vowel on mid stem vowels of the second and third conjugations, as in 'sinto' vs 'sente'.

-   Height harmony in Rio e.g., m[i]nino, f[u]linha.

-   Vowel lowering: higher F1 for [e o] before stressed low-mid vowels.

Stress & Prosodic Grouping:

-   BP stress acoustically predictable from spectrum, not duration nor F0 [@harmath2021detecting]. What cues do heritage PT speakers use for stress? If spectral features are important for stress, we might predict they maintain those vowel distinctions; or, we might predict that they lose the spectral features and pick up different cues for stress (e.g., F0, duration, amplitude).

-   Antepenultimate, penultimate, and final stress are not equally recognizable [@martins1988ouvir]. Penultimate is most frequent and most recognizable; followed by final and antepenultimate. Differs in L1 child acquisition: 5-6 month old EP-learning infants prefer iambic to trochaic stress (opposite of adults), and they pay attention to visual (facial) cues for stress [@cruz2020eyes]. 

-   BP phonological versus morphological word [@camara1992estrutura]. Related to Prosodic Phonology (Nespor & Vogel).

-   Syllable duration and F0 variation as uces for distinguishing prosodic status of prepositional clitic-host sequences from prosodic word sequences in BP [@da2021prosodization]. Phonetic realization of unstressed syllables at prosoidc word boundaries. Duration does not distinguish prosodic word from the clitic prosodization sequences. Does F0 variation signal an intonation associated to clitic-host sequences distinct from prosodic word sequences?

Nasality:

-   Nasal vowels versus nasalized vowels (resulting from coarticulation). Velum opening is gradient, not binary?

Fricative variability:

## @harmath2021detecting

Stress.

## @camara1992estrutura

Book on BP prosody.

## @da2021prosodization

Clitics and prosody. Seems related to @galves2005syntax.

## @martins1988ouvir

Stress perception.

## @cruz2020eyes

L1 acquisition. Eye-tracking. Stress perception.

## @rennicke2015rhotics

Rhotics in Minas Gerais, focus on sound change, Exemplar models, and CASP models. Based on the abstract, I'm getting an articulatory phonology vibe, too: talking about the rhotic class family, articulatory timing, a continuum from alveolar trill to uvular trill, making me think of @lindau1980story.

14 participants from Lavras, Minas Gerais (in the south of the state). Semi-structured interviews and sentence completion task.

Sentence completion task took about 5-10 minutes and were heavily controlled for phonological context and lexical frequency. Since it's already lab speech, maybe we should control for lexical frequency by using nonse words? Stimuli in appendix.

## @da2025reading

10 L1 Spanish L2 Portuguese mid vowel production. Completed two production tasks: "card task" and "list task".

Card task (more cognitively demanding): This is a sentence completion task with images e.g., they see a cup of orange juice, they see the incomplete sentence, "Este é um copo de _____ de laranja", and they have to read the whole sentence with the word filled in twice.

List task (less cognitively demanding): sentence completion task e.g., "Digo _____ com cuidado". 

List task showed greater vowel dispersion, indicating that increased cognitive control may lead to hyperarticulation. 

Stimuli are not available, but maybe we can email them?

## @leite2005atitudes

Rhotic variation in Portuguese with rhotic identification via Praat methodology.

## @leite2010r

Rhotic variation in Portuguese with rhotic identification via Praat methodology.

## @gregio2012variantes

Acoustic analysis of rhotics in coda position. 14 participants, probably not monolinguals (one was an English teacher) (ages 19-58, average = 32), 2 from each: Nordeste, Porto Alegre, Sao Paulo, Interior, Santos, Rio de Janeiro, Belo Horizonte. We should definitely include a map marking city of origin for each participant. 

Task: Sentence reading. For word-final /r/, doesn't give proceeding phonetic context.

Items (all coda /r/):

- word medial, polysyllabic and pretonic (portugueses, percorrido)
- word medial, bisyllabic and tonic (garça, cerca)
- word final, monosyllabic and tonic (ser, por)

Results has nice table of most common manner of articulation of coda /r/ for each variety.

# Topic Summaries

## Clitics

@galves2005syntax

## Portuguese in Newark

@stephens1989language
@carvalho2010portuguese

## /R/

### Production

@rennicke2015rhotics: sentence completion task stimuli in appendix. Acoustic analysis.

@leite2005atitudes: acoustic analysis.

@leite2010r: acoustic analysis.

@gregio2012variantes: acoustic analysis of rhotics in coda position. 

### Perception

## Mid vowels

### Production

@da2025reading: sentence completion task and list-reading task. Stimuli are not available, but maybe we can email them?

### Perception

@osborne2021perception

## Stress

### Production

### Perception

## Stops

@rothman2014portuguese

### Production

### Perception

## Social Networks

@gubitosi2020portuguese

@milroy2013social

Milroy is a major author for Social Network Theory.

# LexTALE used for heritage speakers

@flores2022no
@lozano2025beyond
@alves2025exploring
@zhou2022lextpt

# Misc.

Fernanda A. Ferreira has a lot of research on heritage speakers in college classes.

# Coding Rhotics

This section highlights various methodologies on coding rhotics from production data. The end of this section will include a proposal on how to code rhotics for the present study.

## Impressionistic methodologies

This section is included to highlight the need for acoustics-based studies. We are not using impressionistic methods.

## Acoustic-based methodologies

### @rennicke2015rhotics

"Impressionistic, auditory analysis is insufficient for the analysis of reduction phenomena: sequences can sound intelligible and normal even if several segments cannot be identified in the spectrogram image (Warner 2012, p. 622)."

Summary of other literature:

- Trill
  - succession of light vertical bars (corresponding to closure phases) and darker vertical bars (corresponding to the open or vocalic phases).
  - uvular trills tend to have much higher F3 than alveolar trills
  - uvular trills may be slightly longer than alveolar trills
  
- Taps and flaps
  - one closure, appearing as a light vertical bar
  - tap: tongue tip moved directly towards alveolar ridge
  - flap: tangential strike of tongue tip so that it touches alveolar ridge in passing
  - approximant tap: formant structure is regular and continuous, but at lower amplitude compared to vowels

- Fricatives
  - alveolar, uvular/velar, or glottal
  - random energy distributed over wide range of frequencies; frequencies depend on exact place of articulation
  - acoustic phonetics cannot distinguish uvular vs velar articulations
    - "velar pinch": narrowing of distance between F2 and F3 in adjacent vowels is characteristic of velar consonants (Ladefoged & Johnson 2011, p. 199).
  - glottal fricative does not have the "velar pinch"
  
- Approximants
  - vowel-like formant structure
  - less intensity than vowels
  - formant trajectories can be used to estimate tongue configuration: alveolar, uvular, retroflex, or bunched
  - lowering of F3; high F3 indicates alveolar/uvular constriction
  - typically, "erre retroflexo"/"erre caipira" is referred to as a retroflex, but we don't yet have empirical evidence for this (which would come in the form of articulatory methodologies like palatography, ultrasound imaging, etc.), so "rhotic approximant" is the preferred term
  - retroflex approximant: lowered F3 close to F2; compared to palatal approximants, retroflex approximants have an F3 that is on average slightly lower
  - alveolar approximant: raised F3 closer to F4
  - palatal approximant [j]: rising F2 and F3
  - F3 also depends on preceeding vowel for males: front vowel -> above 2000Hz; back vowels -> below 2000Hz.

- Vocalic variants
  - r-coloured/schwar or neutral schwa-like vowel in syllable coda
  - rhotic vowels: mid-central; F2 and F3 are "conflated"; rhoticity perceived during entire duration of vowel, or only at the end.
  
- Non-rhotic vocalic variants
  - Vowel-Rhotic rhyme can be cued by schwa
  
What was used in this study:

- Tap-like articulation
  - either complete closure phase that shows up in the spectrogram as a light vertical line or a clear release burst.
  - if complete closure is present, can be voiced [ɾ] or voiceless [ɾ̥], determined by presence/absence of voicing bar.
  - if  formants are present, labeled as approximant tap [ɾ̞].

- Fricatives
  - voiced [ɦ] or unvoiced [h] based on presence/absence of voicing bar
  - [χ ʁ] used to represent velar/uvular fricative because spectrogram not suitable for determining precise articulatory location
  - friction noise in "upper end" of spectrogram can be voiced [ɹ̝] or unvoiced [ɹ̝̥]. Weakened variants of apical full-closure rhotics.
  
- Approximants and other vowel-like segments
  - rising F3 = alveolar [ɹ]
  - rising F2, falling F3 = retroflex/bunched [ɻ]
  - rising F2, rising F3 = palatal approximant [j]
  - if F3 was low and perceptual rhoticity was present during (almost) entire duration of syllable nuclear/coda (or when there was no coda) = r-coloured schwa [ɚ]
  
- Aspirated approximants
  - same as above, except with fricative release (e.g., aspiration), represented by superscript h e.g., jʰ

- Deletion
  - no formant changes indicating the presence of a segment other than the vowel in syllable nucleus
  
- Other variants
  - alveolar trill (voiced or voiceless). At least two closure phases (although the alveolar trill can occur with just one closure phase...)
  - lateral approximant [l]
  - voiced labial-velar approximant [w]
  - postalveolar fricatives, voiced and unvoiced

### @blecua2001vibrantes



### @leite2005atitudes

Study focuses on students' language attitudes towards their native variety, focusing on retroflex /r/ in coda position. Native to São José do Rio Preto, São Paulo. Sociolinguistic interviews.

Criteria for acoustic analysis based on "A Course in Phonetics" by Ladefoged (1975), "Rhotics" by Ladefoged & Maddieson (1996), and Lindau's Phonetic Differences in Nigerian Languages (1980) and The story of /r/ (1980).

- retroflex approximant = lowering of F3 approaching F2

### @leite2010r

acoustic analysis.

### @gregio2012variantes

Acoustic analysis of rhotics in coda position.

Criteria for analysis:

- periodicity of signal
- amplitude of signal
- interruption of signal
- noise source identification(? fonte de ruído)
- voicing (I guess via the voicing bar?)
- formant structure (which formants?)
- interruption or continuity of formant structure

### @ferraz2005caracteristicas

### @kiss2013measuring

- Possible measures of phonetic voicing
  - Pulse-based measurements: "Voice Report", based on glottal pulses. Pitch should be set to around 250 Hz to remove "phantom" pulses. This isn't a great method because it's entirely dependent on how much of the sound file is displayed in Praat.
  - Harmonicity (harmonics-to-noise ratio, HNR): can only be used reliably for fricative voicing and other sounds that contain turbulence.
  - Center of gravity (Cog) or spectral mean/centroid: average of frequencies over entire frequency domain weighted by the amplitude. Can be used for place of articulation identification. Can also be used for manner of articulation identification.
  - Duration: voice lengthening etc.
  - Intensity: must be normalized for the recording level and the volume of speech.
  - Zero-crossing rate (ZCR): number of times in a given time interval that the amplitude of the speech signals pass through a value of 0 divided by the number of frames. High values for voiceless fricatives, low values for voiced.
  - Low frequency spectral features: According to Jansen, the fundamental frequency f0 and F1 of a vowel following a voiceless stop and fricative start somewhat higher than the F0 and F1 of a vowel following a voiced stop and fricative.
  
@ladefoged1996sounds

I requested for the rhotics chapter to be digitized for us.
    

## Proposal for coding rhotics

Acoustic values will be extracted from all segments at 10% intervals.

Quantitative measures to be extracted:
  - Formants 1 through 5
  - Duration of segment
  
